import { Employee } from "@/domain/employee/client";

export const EMPLOYEES: Employee[] = [
  {
    id: crypto.randomUUID(),
    name: "Juan Pérez",
    jobTitle: "Gerente de Operaciones",
    email: "perez@example.com",
    phone: "123-456-7890",
    salary: 5000,
    birthDate: "1990-05-15",
    experience: 5,
    address: "Calle Principal 123",
    status: "Activo",
    avatar: "",
    service: "transporte-de-carga",
  },
  {
    id: crypto.randomUUID(),
    name: "María Rodríguez",
    jobTitle: "Ejecutiva de Ventas",
    email: "rodriguez@example.com",
    phone: "987-654-3210",
    salary: 4000,
    birthDate: "1995-10-20",
    experience: 3,
    address: "Avenida Central 456",
    status: "Activo",
    avatar: "",
    service: "mensajeria",
  },
  {
    id: crypto.randomUUID(),
    name: "Carlos Gómez",
    jobTitle: "Técnico de Servicio",
    email: "gomez@example.com",
    phone: "555-123-4567",
    salary: 3500,
    birthDate: "1988-03-12",
    experience: 7,
    address: "Plaza Mayor 789",
    status: "Activo",
    avatar: "",
    service: "documentos-valorados",
  },
  {
    id: crypto.randomUUID(),
    name: "Luisa Morales",
    jobTitle: "Analista de Finanzas",
    email: "morales@example.com",
    phone: "111-222-3333",
    salary: 4500,
    birthDate: "1992-08-05",
    experience: 4,
    address: "Avenida Libertad 789",
    status: "Activo",
    avatar: "",
    service: "servicios-especiales",
  },
  {
    id: crypto.randomUUID(),
    name: "Andrés Fernández",
    jobTitle: "Diseñador Gráfico",
    email: "fernandez@example.com",
    phone: "999-888-7777",
    salary: 3800,
    birthDate: "1993-12-28",
    experience: 2,
    address: "Calle del Sol 456",
    status: "Activo",
    avatar: "",
    service: "servicio-inhouse",
  },
  {
    id: crypto.randomUUID(),
    name: "Ana López",
    jobTitle: "Asistente Administrativa",
    email: "lopez@example.com",
    phone: "777-555-4444",
    salary: 3200,
    birthDate: "1997-02-10",
    experience: 1,
    address: "Avenida Primavera 123",
    status: "Activo",
    avatar: "",
    service: "servicio-aereo",
  },
  {
    id: crypto.randomUUID(),
    name: "Roberto Torres",
    jobTitle: "Ingeniero de Proyectos",
    email: "torres@example.com",
    phone: "444-555-6666",
    salary: 5500,
    birthDate: "1985-06-18",
    experience: 9,
    address: "Calle del Carmen 789",
    status: "Activo",
    avatar: "",
    service: "transporte-de-carga",
  },
  {
    id: crypto.randomUUID(),
    name: "Sofía Silva",
    jobTitle: "Recursos Humanos",
    email: "silva@example.com",
    phone: "333-222-1111",
    salary: 4200,
    birthDate: "1994-04-04",
    experience: 3,
    address: "Avenida del Parque 456",
    status: "Activo",
    avatar: "",
    service: "mensajeria",
  },
  {
    id: crypto.randomUUID(),
    name: "Manuel Vargas",
    jobTitle: "Técnico de Soporte",
    email: "vargas@example.com",
    phone: "777-888-9999",
    salary: 3600,
    birthDate: "1991-11-22",
    experience: 6,
    address: "Calle Principal 789",
    status: "Activo",
    avatar: "",
    service: "documentos-valorados",
  },
  {
    id: crypto.randomUUID(),
    name: "Laura Mendoza",
    jobTitle: "Abogada",
    email: "mendoza@example.com",
    phone: "555-444-3333",
    salary: 4800,
    birthDate: "1989-09-14",
    experience: 8,
    address: "Avenida Central 123",
    status: "Activo",
    avatar: "",
    service: "servicios-especiales",
  },
  {
    id: crypto.randomUUID(),
    name: "Felipe Castro",
    jobTitle: "Asesor de Ventas",
    email: "castro@example.com",
    phone: "222-333-4444",
    salary: 3900,
    birthDate: "1996-07-30",
    experience: 2,
    address: "Plaza Principal 456",
    status: "Activo",
    avatar: "",
    service: "servicio-inhouse",
  },
  {
    id: crypto.randomUUID(),
    name: "Daniela Rojas",
    jobTitle: "Contadora",
    email: "rojas@example.com",
    phone: "999-777-5555",
    salary: 4300,
    birthDate: "1998-01-05",
    experience: 1,
    address: "Avenida Libertad 789",
    status: "Activo",
    avatar: "",
    service: "servicio-aereo",
  },
];
